In [66]:
import pandas as pd 
import os 
import numpy as np
from openpyxl import load_workbook
import xlsxwriter

In [15]:
# Read the files 
file = "/Users/doristai/Documents/GitHub/final_project/Resources/cancer_patient_data_sets_with_scores(1).xlsx"

In [16]:
raw = pd.read_excel(file)
raw.head()

,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,Obesity,...,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level,Score
0,35,1,4,5,6,5,5,4,6,7,...,7,9,2,1,4,6,7,2,High,5.000000
1,37,1,7,7,7,7,6,7,7,7,...,2,3,1,4,5,6,7,5,High,5.761905
2,46,1,6,8,7,7,7,6,7,7,...,2,4,1,4,2,4,2,3,High,5.285714
3,35,1,4,5,6,5,5,4,6,7,...,7,9,2,1,4,6,7,2,High,5.000000
4,44,1,6,7,7,7,7,6,7,7,...,3,2,7,8,2,4,5,3,High,5.809524

In [48]:
# High risk profile
high_risk = raw[raw['Level'] == 'High']
high_average = np.mean(high_risk['Score'])
high_first_qrt = np.percentile(high_risk['Score'], 25)
high_second_qrt = np.percentile(high_risk['Score'], 50)
high_third_qrt = np.percentile(high_risk['Score'], 75)
iqr = high_thrid_qrt - high_first_qrt
high_risk_max = max(high_risk['Score'])
print(f'High Risk Patients Stats : \nmax : {high_risk_max}\n25% : {high_first_qrt}\nmean : {high_second_qrt}\n75% : {high_thrid_qrt}\nIQR : {iqr}')

High Risk Patients Stats :
max : 6.571428571428571
25% : 5.285714285714286
mean : 5.714285714285714
75% : 5.904761904761905
IQR : 0.6190476190476195

In [49]:
# Medium risk profile
medium_risk = raw[raw['Level'] == 'Medium']
medium_average = np.mean(medium_risk['Score'])
medium_first_qrt = np.percentile(medium_risk['Score'], 25)
medium_second_qrt = np.percentile(medium_risk['Score'], 50)
medium_third_qrt = np.percentile(medium_risk['Score'], 75)
medium_iqr = medium_thrid_qrt - medium_first_qrt
medium_risk_max = max(medium_risk['Score'])
print(f'Medium Risk Patients Stats : \nmax : {medium_risk_max}\n25% : {medium_first_qrt}\nmean : {medium_second_qrt}\n75% : {medium_thrid_qrt}\nIQR : {medium_iqr}')

Medium Risk Patients Stats :
max : 4.857142857142857
25% : 3.3333333333333335
mean : 4.190476190476191
75% : 4.523809523809524
IQR : 1.1904761904761902

In [50]:
# Low risk profile
low_risk = raw[raw['Level'] == 'Low']
low_average = np.mean(low_risk['Score'])
low_first_qrt = np.percentile(low_risk['Score'], 25)
low_second_qrt = np.percentile(low_risk['Score'], 50)
low_third_qrt = np.percentile(low_risk['Score'], 75)
low_iqr = low_thrid_qrt - low_first_qrt
low_risk_max = max(low_risk['Score'])
print(f'Low Risk Patients Stats : \nmax : {low_risk_max}\n25% : {low_first_qrt}\nmean : {low_second_qrt}\n75% : {low_thrid_qrt}\nIQR : {low_iqr}')

Low Risk Patients Stats :
max : 4.571428571428571
25% : 2.2857142857142856
mean : 2.5714285714285716
75% : 2.761904761904762
IQR : 0.4761904761904763

In [52]:
data = {'Level' : ['High', 'Medium', 'Low'],
        'Mean': [high_average, medium_average, low_average],
        '1st Percentile' : [high_first_qrt, medium_first_qrt, low_first_qrt],
        '3rd Percentile' : [high_third_qrt, medium_third_qrt, low_third_qrt],
        'IQR' : [iqr, medium_iqr, low_iqr]
}

summary_df = pd.DataFrame(data)
summary_df

    Level      Mean  1st Percentile  3rd Percentile       IQR
0    High  5.600391        5.285714        5.904762  0.619048
1  Medium  3.959122        3.333333        4.523810  1.190476
2     Low  2.663209        2.285714        2.761905  0.476190

In [76]:
writer = pd.ExcelWriter('patients_stats_by_level.xlsx')
high_risk.describe().transpose().to_excel(writer, 'High')
medium_risk.describe().transpose().to_excel(writer, 'Medium')
low_risk.describe().transpose().to_excel(writer, 'Low')
writer.save()